name: Clock
version: ${project.version}
main: jp.eximradar.keitan.time.Time
api-version: 1.16
authors: [keitan]
description: Time Check Tool

commands:
  ping:
    description: ping pong.
    usage: /ping
  time:
    description: show now time.
    usage: /time